### ISSUE TITLE
Transferring crate ownership

### ISSUE THREAD

**Issue by tyranron** [mmitteregger/gherkin-rust#1]
Hi, @mmitteregger!

Speaking for a [`cucumber-rs` team](https://github.com/cucumber-rs/) owning [`cucumber`](https://docs.rs/cucumber) and [`gherkin-rust`](https://docs.rs/gherkin-rust) crates, providing a pure Rust Cucumber implemenation (and the only actively maintained afaik), we want to kindly ask you to transfer us the ownership of [`gherkin`](https://docs.rs/gherkin/0.0.1) crate.

Its description says it's just squoted for a future use and doesn't contain any actual code yet. Considering the pulse of this repository we may conclude, that it unlikely will be used in future. So, we would be happy to rename our `gherkin-rust` crate to a simpler and more obvious `gherkin`, if you don't have any serious plans for it.

**Comment by mmitteregger** [comment]
Hi @tyranron,

Thanks for reaching out to me and sorry for the late response.
Your conclusion is correct, I do not plan to invest a lot of time into maintaining this.
I've already thought about doing this in the past and am very happy that [cucumber-rs](https://github.com/cucumber-rs) exists and is well maintained.
Therefore I am willing to transfer ownership of the gherkin crate to your team.

According to the [crates.io documentation](https://crates.io/policies#package-ownership) I only have to add a new owner username to the package on the website. Afterwards you can (and should) remove me to avoid potential security issues.

I've only added you - [tyranron](https://crates.io/users/tyranron) - for now. You should have gotten an invite.
Please add the other owners (probably bbqsrc and ilslv) yourself.

**Comment by tyranron** [comment]
@mmitteregger thank you!
